beam-community/ex_machina

lib/anvil.ex
test/anvil_test.exs

* build/2
* create/2
* create_pair/2
* create_list/2
* assoc/2

Add initial functions

---

lib/ex_machina/ecto.ex
test/ex_machina/ecto_test.exs

Right now the error message is not that helpful. This makes it a bit
more clear what is wrong, and how to resolve the issue.

Improve error when no repo is given

---

lib/ex_machina.ex
lib/ex_machina/ecto.ex

This should make it easier to override each function within your own
test suite.

Move functions from use to before compile

---

README.md

Someone mentioned they didn't realize that what the second attrs were until they tried it. I think it would be helpful to add something to the README

Add docs about what `attrs` are used for

---

README.md

README - Where to put factories

---

README.md

@josevalim I've added the 3 separate installation instructions in #87 so I'll go ahead and close that PR.
I also changed "Where to put factories" and moved "usage in a test" closer to the overview since I think it fits in with that section.

Update installation instructions and move around "usage in a test"

---

circle.yml
lib/ex_machina.ex
mix.exs
test/ex_machina_test.exs

Raise if passing invalid keys to structs

---

lib/ex_machina.ex

Remove unused save_record code

---

README.md

Include note about README being out of date

---

README.md

We love working with Elixir and Phoenix and want to call attention
specifically to our experience with those technologies. Our
`elixir-phoenix` landing page has open source projects, blog posts, and
information on why we love Elixir.

Promote thoughtbot's Elixir experience

---

CHANGELOG.md
lib/ex_machina.ex
mix.exs

Remove prepended colon from factory error

---

mix.exs

Hi! First of all, thank you for your very nice tool! I just want to fix small but annoying warnings, since i'm using elixir 1.4-dev and phoenix and every time at phoenix starting, i got bunch of warnings. I hope this is not distracting

Fix most annoying elixir 1.4 warnings

---

README.md

Added tutorial for splitting factories into multiple files

---

mix.exs

See discussion:
https://github.com/thoughtbot/ex_machina/commit/1dfa863086c9f24c27fd22988e6df5733d844174#commitcomment-21271957

Specify Ecto dep once

---

lib/ex_machina.ex
lib/ex_machina/ecto.ex

* recrod -> record
* Kernal -> Kernel

Fix broken build due to typos

---

lib/ex_machina.ex
lib/ex_machina/strategy.ex
test/ex_machina/ecto_test.exs
test/ex_machina_test.exs

handle the number 0 in build_list and insert_list

---

README.md
mix.exs

It also updates the README to show `2.1.0`

Update ex_machina version in mix.exs to 2.1.0

---

README.md

Addresses issue: https://github.com/thoughtbot/ex_machina/issues/255

Changed reference of Factory Girl to Factory Bot

---

lib/ex_machina.ex

Fixed mistake in the comment for the example usage of sequence/2

Update documentation for sequence/2

---

README.md

Just small clarification to adding ex_machina as application setup step

Clarify skipping application step of setup

---

README.md

Similar to https://github.com/thoughtbot/ex_machina/pull/239
This seems obvious now, but I puzzled over how to do it at first because I imagined `sequence` to be some DSL magic and not a function I could call outside of building the struct.

README: Show example of a derived attribute

---

test/ex_machina/ecto_strategy_test.exs
test/support/models/user.ex

Fix test setup

---

README.md

Update due to current practice of directory structure

Remove "web" dir from README.md

---

README.md

I didn't understand why my file was not loaded when I moved some factories to a new location while following this README. 
This should help future users.

Update README.md with information about compiling factories in tests.

---

lib/ex_machina/ecto.ex
lib/ex_machina/sequence.ex

This should fix CI errors introduced in this previous commit: https://github.com/beam-community/ex_machina/commit/72e40389a273a38be5f8dd96aef02976258212aa#diff-6ca71cb4f078103fdc4b89f2d36a029938817240fabb57ab6b72fafe463c7907R272

fix: revert code changes breaking ecto record loading

---

README.md

Need to go through all of the transferred repos and look for lingering Thoughtbot references.

chore: Update Thoughtbot to BEAM Community
