beam-community/ex_machina

README.md, lib/ex_machina.ex, mix.exs
Make README the in-depth, authoritative source for examples.
=> Shorter example in main module, long one in README

README.md, lib/ex_machina.ex, lib/ex_machina/ecto.ex, test/ex_machina/ecto_test.ex, test/ex_machina_test.exs
This should make it easier to add other adapters in the future and
reduces the need for conditionals due to separation of concerns.
=> Extract all Ecto functionality to separate module

test/ex_machina/ecto_test.exs
The test file left off the `s` at the end so it wasn't being run by `mix
test`. This adds the `exs` extension and fixes the broken tests
This was already reviewed in https://github.com/thoughtbot/ex_machina/pull/13, I'm just splitting it out into it's own PR and merging it in
=> Fix broken Ecto tests

README.md
We changed this to be `save_record`, but forgot to update the README
=> Update README to use `save_record`

lib/ex_machina.ex, test/ex_machina_test.exs
This will allow things like:
```
build(:user, name: "john") |> on_free_trial |> create |> add_comment(title: "toto")
```
So that you can easily modify the built record, then call create and do `has_many/has_one` relationships with the saved record. I will be adding the functionality to not save associations on build in the next PR, which should make this a bit more robust
=> Allow chaining with built records

README.md, lib/ex_machina.ex, lib/ex_machina/ecto.ex
* Removes warning when defining custom save_record/1 function
* Removes unnecessary `module` param in `ExMachina.Ecto.save_record`
* Corrects docs. `save_function/1` to `save_function/2`
Closes #22
=> Cleaning up warnings

README.md, lib/ex_machina.ex, test/ex_machina_test.exs
Even if the Phoenix team decides not to import `build` by default it might make sense to include this since people that already have a generated Phoenix application would have the `Eco.Model` import.
=> Add note about importing with Phoenix

lib/ex_machina.ex, lib/ex_machina/ecto.ex, test/ex_machina/ecto_test.exs
This PR makes it so records, including associations, are only saved in `save_record`. There is no reason to save the records on the build step, so this will save unnecessary writes, while making build more intuitive.
=> Don't save associations in build

config/config.exs, lib/ex_machina/ecto.ex, test/ex_machina/ecto_test.exs
This fixes an error where a factory has an association, but the record
is not set in the factory definition or passed in when creating the
factory. Since associations are structs of type
`Ecto.Association.NotLoaded`, we can ignore these and return the record
as is.
=> Ignore associations that are not set

lib/ex_machina/ecto.ex, test/ex_machina/ecto_test.exs
Before this was only setting the association's id when saving a built
record, but that meant that the association still had the built record,
not the newly saved one. This makes sure that `put_assoc` set both the
id, and the associated record
=> Fix association bug

README.md, lib/ex_machina.ex, lib/ex_machina/ecto.ex, test/ex_machina/ecto_has_many_test.exs, test/ex_machina/ecto_test.exs, test/ex_machina_test.exs
Functions have less complexity and less magic than normal functions.
The functional approach also provides access to the `attrs` hash, which
allows you to utilize it in your factory definition:
def factory :user, attrs do
modified_attrs = attrs |> modify_attrs
%{
name: "Foobar",
accounts: assoc(modified_attrs, :accounts),
}
end
=> Return to using functions for factory definitions

test/ex_machina/ecto_has_many_test.exs, test/ex_machina/ecto_test.exs, test/ex_machina/sequence_test.exs, test/ex_machina_test.exs
Some of the other tests are running asynchronously and were causing
issues if they both used the same sequence name (in this case `email`).
Running the tests synchronously should fix the issue.
The tests are still plenty fast. Once Ecto supports concurrent tests, we may want to rethink the Sequence module so that it keeps sequences *per process* so others don't run into this issue with their tests. Fixes #44
=> Fix intermittent failure

mix.exs, priv/test_repo/migrations/20151030144844_add_settings_to_users.exs, test/ex_machina/ecto_embeds_test.exs
This covers behavior added in 080498ee4c3a5a70b69f478c7877d2979e879e01
Also updated mix.exs so that a migration could be generated during development without prefixing with MIX_ENV=test.
=> Tests for saving embedded Ecto models

README.md
I wanted to keep all my factories in `test/factories` folder, which is not loaded by default in the Phoenix framework. I think this information might be useful in the readme.
=> Add info about preloading factories to README.md

README.md
Users should start `ex_machina` in `test/test_helper.exs` rather than modifying the applications list in `mix.exs`.
=> Update instructions to start ex_machina in the test env

test/ex_machina_test.exs
This test says its supposed to merge a map, but it was a keyword list.
=> Fix test data to match with the test description

mix.exs
ExMachina currently doesn't show up on hex.pm if you search for "factory" or
"factories". I'd like to at least appear on that list. There are some
other libraries that do show up and mention that they are clones of
FactoryGirl. That seems to be something people are interested in, so it
may be worth saying that this is from the same people who created
FactoryGirl.
=> Improve mix description

lib/ex_machina.ex, test/ex_machina_test.exs
Previously, the error message defined in `factory/2` would not be used
because internally we were only calling `factory/1`. This improves the
error message and moves it to the appropriate spot.
Addresses: https://github.com/thoughtbot/ex_machina/issues/63
=> Actually display error message

lib/ex_machina/ecto.ex, mix.exs, mix.lock
Using the internal function Ecto.Association.loaded? no longer works. Fortunately there's a public function for the same thing Ecto.assoc_loaded? now
This makes #70 work (but with deprecation warnings still).
=> Upgrade ecto

lib/ex_machina/ecto.ex, test/ex_machina/ecto_has_many_test.exs
This breaks apart the general use of `Ecto.Changeset.change` when building records. Instead, it uses `put_assoc` and `put_embed`, eliminating the deprecation warnings in Ecto 1.1.
=> Use put_assoc/4 and put_embed/4 when building records

CHANGELOG.md, README.md, mix.exs
This version bump requires Ecto 1.1 (required since ExMachina 0.6.0). This version removes the deprecation warnings generated by Ecto 1.1
=> Update version to 0.6.1

lib/ex_machina.ex, lib/ex_machina/sequence.ex, test/ex_machina/sequence_test.exs, test/ex_machina_test.exs
=> Add Sequence.next/1 for quickly creating sequences

README.md, lib/ex_machina/ecto.ex, test/ex_machina/ecto_test.exs
This reads much more nicely IMO
```elixir
post comment_path(conn, :create), params_for(:comment)
assert Comment.changeset(%Comment{}, params_for(:comment)).valid?
```
=> Rename fields_for to params_for

README.md, lib/ex_machina.ex, lib/ex_machina/strategy.ex, mix.exs, test/ex_machina/ecto_strategy_test.exs, test/ex_machina/ecto_test.exs, test/ex_machina/strategy_test.exs, test/ex_machina_test.exs
Pros
* Can use symbol view/ctags to jump to the factories more easily
* Can add helper functions underneath the factory they belong to
* IMO it's easier to scan your factory module for a particular factory
* Easier to type :)
* If/when callbacks are introduced, this will allow you to put the
callback functions near the factory
Cons
* A little more *magic* since you still call the functions with atoms,
e.g.`build(:user)`
Closes #101
=> Use new factory definition syntax

lib/ex_machina.ex, lib/ex_machina/sequence.ex, test/ex_machina/sequence_test.exs, test/ex_machina_test.exs
Closes #108
This makes it so the sequence short function can be used for things like
usernames where a space will make the username invalid.
=> Omit trailing space from sequence shortcut

lib/ex_machina/ecto_strategy.ex, lib/ex_machina/strategy.ex, test/ex_machina/strategy_test.exs
Options passed to handling functions are now a map which makes it easier
to pattern match. It also includes the calling factory module in the
options.
name_from_struct/1 is added so that people can create strategies that
define callbacks or need to call other functions with the factory name.
Closes #111. See discussion for more details on why this strategy was
chosen.
=> Add name_from_struct for strategies

README.md
I think this is important since a lot of people are moving to Ecto 2.0 lately. I'm hoping to release ExMachina 1.0 when Ecto 2.0 ships
=> Update README to include installing from GitHub

lib/ex_machina/ecto.ex, test/ex_machina/ecto_test.exs
I can't think of any use case where you would want the id field when
using params_for. For something scenarios like submitting to an API, or
getting the bare fields to test validations it would be rare to
actually submit the id itself, and so the current behavior feels
unexpected.
=> Don't return id field in params_for

test/test_helper.exs
Now that we are using a single file for migrations, we should drop the
database each test run to get the new schema.
=> Drop the database for each test run

lib/ex_machina/ecto_strategy.ex, test/ex_machina/ecto_strategy_test.exs
Hey there, so I think this one is good to go.
Note, I split handle_insert function per @paulcsmith comment in #90 
```
def handle_insert(%{__meta__: %{state: :loaded}} = record, _) do
raise ArgumentError,
"you called `insert` on #{inspect record} but it has already been saved.
You can only call `insert` on records that haven't been inserted yet"
end
def handle_insert(%{__meta__: %{__struct__: Ecto.Schema.Metadata}} = record, %{repo: repo}) do
repo.insert!(record)
end
```
Note: I rebased with the latest test changes from @jsteiner regarding Factory -> TestFactory
Let me know if it needs anything else. Cheers!
=> Fix #90 Insert Twice

README.md
If an Elixir / Phoenix novice (like me) follows these instructions literally, structs defined in `factory.ex` will not be defined correctly
This updates `README.md` to include the required `alias` statements in context
=> Fix undefined struct error

README.md, lib/ex_machina/ecto.ex, priv/test_repo/migrations/1_migrate_all.exs, test/ex_machina/ecto_test.exs, test/support/factory.ex, test/support/models/article.ex, test/support/models/user.ex
Addresses: https://github.com/thoughtbot/ex_machina/issues/105
=> Add params_with_assocs function

README.md, lib/ex_machina.ex, lib/ex_machina/strategy.ex, test/ex_machina_test.exs
Hey @paulcsmith:
**Codebase changes:**
1. [`create` functions with error-helpers](https://github.com/davidkuhta/ex_machina/blob/error-helpers/lib/ex_machina.ex#L53) 
**Tests:**
Split based on arity to match the pattern of existing tests:
1. [`create/2`, `create_pair/2`, `create_list/3` tests](https://github.com/davidkuhta/ex_machina/blob/error-helpers/test/ex_machina_test.exs#L102)
2. [`create/1` test](https://github.com/davidkuhta/ex_machina/blob/error-helpers/test/ex_machina/ecto_strategy_test.exs#L57)
**Other:**
1. Corrected two comments which had `_list/2` instead of `_list/3`
Cheers!
=> Fix #106 - ExMachina.create functions error helpers

README.md
There was a typo in the README in the `params_with_assocs` section.
=> Fix typo in README (params_with_assocs)

README.md
Small tweak to `README.md`; Changing 'for non Phoenix projects' to 'for non-Phoenix projects'.
=> README edit: 'non Phoenix projects' to 'non-Phoenix projects'

lib/ex_machina.ex
There is an issue with ExMachina when used with OTP 19
```
== Compilation error on file test/support/test_factory.ex ==
** (ArgumentError) argument error
(stdlib) erl_anno.erl:318: :erl_anno.set(:file, 'nofile', -1)
(stdlib) erl_parse.yrl:1516: anonymous fn/3 in :erl_parse.map_anno/2
(stdlib) erl_parse.yrl:1631: :erl_parse.modify_anno1/3
(stdlib) erl_parse.yrl:1517: :erl_parse.map_anno/2
(stdlib) erl_lint.erl:703: :erl_lint."-set_file/2-lc$^0/1-0-"/2
(stdlib) erl_lint.erl:448: :erl_lint.exprs_opt/3
(stdlib) erl_eval.erl:173: :erl_eval.check_command/
```
By removing the `lineL -1` the issue goes away. There is also no warning
when doing this so it can be safely removed.
=> Fix compilation issue under OTP 19

lib/ex_machina.ex, lib/ex_machina/sequence.ex, test/ex_machina/sequence_test.exs
Closes https://github.com/thoughtbot/ex_machina/issues/120
`Sequence.reset` can be run in a `setup` block to make sure sequences
are reset between tests. This often times is not needed, but when it is,
it's handy to have. See the linked issue above for more details.
=> Add Sequence.reset

README.md
Looks like it was just missing a `:`
=> Fix typo in `insert_pair` example

lib/ex_machina.ex
Applications which include ex_machina and run dialyzer receive warnings
about functions that have no possibility of being called without raising
an exception. Adding these specs fixes those warnings.
=> Add specs to resolve dialyzer warnings

lib/ex_machina/ecto.ex, test/ex_machina/strategy_test.exs
In Elixir 1.4, local arity 0 functions which are called without parentheses raises a warning. Just a quick PR to satisfy these warnings by explicitly using parentheses where applicable.
=> Fix a couple of new Elixir 1.4 warnings

README.md
Mix v1.4 now automatically infers the applications list
as long as you leave `:applications` key empty
=> docs application dependency update for elixir 1.4

lib/ex_machina/ecto.ex, test/ex_machina/ecto_test.exs, test/support/models/user.ex
Drop unbuilt has many throughs in params functions
Prior to this commit, a has_many through relationship on the model was not dropped from the model. We now delete unbuilt has-many throughs.
Since we already test expected output from various params functions, simply adding the has_many through relation to the model was enough to reproduce errors in the tests.
=> Drop unbuilt has many throughs in params functions

lib/ex_machina/ecto_strategy.ex, test/ex_machina/ecto_strategy_test.exs
Previously the catchall was falling through to the list case and trying
to enumerate `nil`. This commit adds a guard to the list condition to
ensure that doesn't happen again, then adds a new condition to handle
`nil`.
I _think_ this should be handling all cases now, so it also removes the
catchall. This way, if it fails in a way we didn't expect, it should
give an obvious failure that there was no matching case.
Fixes https://github.com/thoughtbot/ex_machina/issues/191
=> Allow setting associations to nil

README.md
Being new to Phoenix I spent some time this morning trying to figure out why I got the error `undefined function insert/1` when setting up ExMachina. Turns out I'd put the `import MyApp.Factory` into the body of MyApp.ConnCase instead of in the `using` block. 
This PR adds a note to the readme in the hope of saving other developers the time it took to figure that out.
Thanks for the great library!
=> Clarify where to import factory module in Phoenix

README.md
I clicked on the link to the *docs for the latest published version of ExMachina* and hexdocs.pm gave me a 404. Turns out `README.html` should be `readme.html`. This PR fixes the link.
Let me know if I should open an issue. I did not open an issue in the first place, because I felt this is a really minor fix.
=> Fix link to latest published docs

lib/ex_machina/ecto_strategy.ex, test/ex_machina/ecto_strategy_test.exs
Found this while debugging #206 - in Elixir you can only interpolate values if they implement the `String.Chars` protocol.
=> EctoStrategy: Fix error message in cast_value/3

lib/ex_machina/ecto.ex, test/ex_machina/ecto_test.exs, test/support/models/comment.ex
I had an issue that `params_for` didn't work for my model that had embed fields in it; you have to strip embed structs down to plain maps for them to be allowed inside a changeset.
I removed the pattern matching dealing with `Ecto.Schema.Metadata` because `embedded_schema`s don't have metadata; it should always be safe as all traversed objects have Ecto schemas by the context of the `recursively_strip` method.
=> Strip embeds in params_for

lib/ex_machina/ecto_strategy.ex, priv/test_repo/migrations/1_migrate_all.exs, test/ex_machina/ecto_strategy_test.exs, test/support/models/article.ex, test/support/models/comment.ex
The first one was only supported for assocs. 
Passing a bare map for an embed first crashed in `cast_value` because it can't be cast trivially, then in `cast_assoc` because the bare map handling code expects an association only.
The second one wasn't supported for either assocs or embeds, because bare maps inside of the list weren't properly casted.
Added tests and fixed.
=> Ecto: Support bare maps as values for embeds. Support lists of bare maps

lib/ex_machina/ecto_strategy.ex
* Renamed `embed_field?` variable to `embedded_field?`
* Extracted branching logic into `cast_assoc/3` for the case when the association is
a list.
=> Minor clean up of EctoStrategy

lib/ex_machina/ecto.ex, test/ex_machina/ecto_test.exs
Add support for `.string_params_for/2` to handle nested associations and
nested embeds: `has_one`, `has_many`, `embeds_one`, and `embeds_many`.
I believe this addresses https://github.com/thoughtbot/ex_machina/issues/222, and https://github.com/thoughtbot/ex_machina/issues/215
=> Handle nested structures in `string_params_for/2`

lib/ex_machina/ecto.ex, test/ex_machina/ecto_test.exs
I just tried out using the master branch for embeds in `params_for/2` and encountered unexpected behavior. In my current project I already have calls like `prams_for(:product, weight: %{value: 10, unit: "kg"})` and this fails in `recursively_strip/1`.
This PR fixes the issue.
=> Fixes issue with passing maps for embeds to params_for/2

lib/ex_machina/ecto.ex, test/ex_machina/ecto_test.exs, test/support/models/money.ex
Summary
=======
`string_params_for/2` currently fails when a struct is passed for a
field. The error comes when a function from the enumerable protocol is
called on the struct (assuming it's a plain map). So the following
example would fail,
```elixir
Factory.string_params_for(:model, some_field: %SomeStruct{key: value})
```
The behavior of `string_params_for/2` with a struct should be to convert
it into a plain map with strings as keys. So in the example above, we
would expect the result from `string_params_for/2` to include
`%{"some_field" => %{"key" => value}}`
This commit does this by using `Map.from_struct/1` to turn the struct
into plain map before continuing with the process of converting the
atoms into strings.
I believe this takes care of …
=> Support structs in string_params_for/2

lib/ex_machina/ecto_strategy.ex
Summary
=======
`Ecto.Schema` has a `__schema__/1` function that allows us to
instrospect which fields are non-virtual, which are embeds, and which
are associations.
We already make use of this `__schema__` function for determining
associations and embeds, but the code seemed somewhat complicated in
that when we cast fields, we had to know to skip associations and
embeds by checking each fields type. By using `__schema__(:fields)` and `__schema__(:embeds)` we are able to cast fields first, then embeds, and finally associations.
This has the advantage of allowing us to untangle associations and
embeds code which, although is somewhat similar, does not overlap
completely (there are more conditions to check when casting
associations).
=> Refactor Ecto.Strategy to use Ecto.Schema reflections

README.md, lib/ex_machina.ex, lib/ex_machina/sequence.ex, test/ex_machina/sequence_test.exs
Now we can use list sequences, as proposed in #223
```
def user_factory do
%MyApp.User{
name: "Jane Smith",
email: sequence(:email, &"email-#{&1}@example.com"),
role: sequence(:role, ["admin", "user", "other"]),
}
end
```
=> So that we can use list sequences, fixes #223

lib/ex_machina/strategy.ex
`Regex.split/3`'s behavior was [changed in Elixir 1.6]( https://github.com/elixir-lang/elixir/issues/7385) and caused `ExMachina.Strategy.underscore/1` to return an extra underscore and broke all factory names that are generated by `ExMachina.Strategy.name_from_struct/1`.
This PR does ~2 things~ 1 thing:
- ~Fixes the regex inside `ExMachina.Strategy.underscore/1` to do negative lookbehind for a start of line.~
- ~Use a single `Regex.replace/4` instead of `Regex.split/3` + `Enum.join/2` which, [according to Jose Valim, is equivalent](https://github.com/elixir-lang/elixir/issues/7385#issuecomment-367969050).~
- Use [`Macro.underscore/1`](https://hexdocs.pm/elixir/Macro.html#underscore/1) instead of `Regex.split/3` + `Enum.join/2` to convert module name to snake case. (Thanks @vernomcrp for …
=> Update underscore/1 to support Elixir 1.6's regex

CHANGELOG.md, README.md, mix.exs
Bump version to 2.2.0. Notable changes include,
- Support for lists in sequences (PR #227)
- Using `Macro.underscore/1` so that factory names don't break in elixir
1.6 (PR #275)
=> Bump version to 2.2.0

mix.exs
Because we use `List.pop_at` from #227, we require the project to run with Elixir 1.4.0 or higher. This reports ex_machina correctly. [List.pop_at was introduced in Elixir 1.4.0
](https://github.com/elixir-lang/elixir/blob/v1.4/CHANGELOG.md)
=> Bump Elixir Requirement to >= 1.4.0

lib/ex_machina.ex
sequence/2 can receive a list as second argument, but right now the typespec does not reflect that.
=> Add list to typespec for sequence/2

lib/ex_machina/ecto.ex
Fixes #157
Since version 1.0.0, when users of ex_machina try to call the deprecated `fields_for/2` function, it raises an exception. This doesn't seem to provide any benefit. If instead it's removed, calls to it will fail at compile time. But if it stays in, calls will fail at runtime, possibly in production.
This PR solves the Dialyzer issue and it provides a better solution for dealing with the obsolete function.
=> Remove obsolete `fields_for/2` function

README.md, lib/ex_machina.ex, test/ex_machina_test.exs
Closes: https://github.com/thoughtbot/ex_machina/issues/309, https://github.com/thoughtbot/ex_machina/issues/272, https://github.com/thoughtbot/ex_machina/issues/271
Description
-----------
Currently `build(:user)` will grab the struct/map defined in `user_factory/0` and merge any attributes passed into it via `struct!/2` or `Map.merge/2`. 
It would be nice to allow users to have more control of factories if they want to, while maintaining the ease of use for the majority of cases. It seems this can be done by allowing users to change the `user_factory/0` to a factory that takes in the attributes being passed in.
We can do so by checking if they have defined a factory with `/1` arity (meaning they allow parameters to be passed).
Example
---------
Let's take a look at a scenario where this …
=> Allow more control over factory definitions

test/ex_machina/ecto_strategy_test.exs
`Decimal.new/1` was throwing a deprecation warning,
> passing float to Decimal.new/1 is deprecated, use Decimal.from_float/1 instead
We update the appropriate tests to use `Decimal.from_float/1`.
=> Use Decimal.from_float/1 instead of Decimal.new/1

lib/ex_machina/sequence.ex, test/ex_machina/sequence_test.exs
Fixed docs and create `reset/1` which can receive a list with sequence names or a single sequence name. This will reset to 0 the sequence names in the list and leave any other sequence with the current index.
=> Add reset/1 with the option to reset specific sequences at once

lib/ex_machina.ex
Hey guys, just a simple indentation adjust in the documentation for `merge_attributes/2` function.
Before:
After:
=> Fix indentation for doc example

lib/ex_machina/ecto.ex, lib/ex_machina/ecto_strategy.ex, test/ex_machina/ecto_test.exs
We should be able to use Ecto without a repo. This is useful when using `ecto` without `ecto_sql`.
ExMachina currently raising an ArgumentError when using ExMachina.Ecto without a repo. This change now allows the repo to be nil and raises a RuntimeError when the insert/1 function is called instead.
New error message should still be helpful enough for people that simply forgot to add the :repo option.
```
insert/1 is not available unless you provide the :repo option. Example:
use ExMachina.Ecto, repo: MyApp.Repo
```
I believe this addresses the following issues:
https://github.com/thoughtbot/ex_machina/issues/369
https://github.com/thoughtbot/ex_machina/issues/355
=> Allow ExMachina.Ecto to be used without the :repo option

mix.exs
FactoryGirl hasn't been named as such for quite a while. I've preserved the name in the commit to ensure this library is still found when searching for something along the lines of "elixir factorygirl".
=> Update Reference to Prior Art

lib/ex_machina/strategy.ex
This PR fixes the compilation warning produced by Ex Machina under Elixir 1.11.
Closes #398
=> Fix Elixir 1.11 compilation warning

mix.exs
I'm getting the following warning after upgrading to elixir 1.11. Related #398 #399.
```
warning: Ecto.Type.cast/2 defined in application :ecto is used by the current application but the current application does not directly depend on :ecto. To fix this, you must do one of:
1. If :ecto is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs
2. If :ecto is a dependency, make sure it is listed under "def deps" in your mix.exs
3. In case you don't want to add a requirement to :ecto, you may optionally skip this warning by adding [xref: [exclude: Ecto.Type]] to your "def project" in mix.exs
lib/ex_machina/ecto_strategy.ex:62: ExMachina.EctoStrategy.cast_value/3
```
By default, the list of applications to start is automatically inferred …
=> Fix elixir 1.11 warning by using extra_applications

README.md, lib/ex_machina.ex, priv/test_repo/migrations/1_migrate_all.exs, test/ex_machina/ecto_test.exs, test/ex_machina_test.exs, test/support/models/publisher.ex, test/support/test_factory.ex
Closes #402, #385, and #373
The problem
------------
People often run into this problem: they want a different email per account, but they do this:
```elixir
build_pair(:account, email: build(:email))
```
The problem is that `build/2` is just a function call. So the above is equivalent to this:
```elixir
email = build(:email)
build_pair(:account, email: email) # same email
```
In other words, we get the same email factory for all of the accounts. That's especially confusing if we're using a `sequence` in the `email` factory.
The problem is made worse when using it with Ecto. We can imagine the following scenario:
```elixir
insert_pair(:account, user: build(:user))
```
If the user factory has a uniqueness constraint, `insert_pair/2` will raise an error because we'll try to insert a user …
=> Allow delayed evaluation of attributes

README.md
This update all links to HTTPS and also fix broken link.
=> Always use HTTPS for links

lib/ex_machina.ex, lib/ex_machina/sequence.ex, test/ex_machina/sequence_test.exs, test/ex_machina_test.exs
Closes: https://github.com/thoughtbot/ex_machina/issues/214
What changed?
============
We introduce `ExMachina.sequence/3` that allows for passing the `start_at` option to set a starting point for a sequence.
This is meant to be used in a factory definition:
```elixir
def money_factory do
%{
cents: sequence(:cents, &"#{&1}", start_at: 60)
}
end
```
Then, the following would increment starting at 60:
```elixir
build(:money)
// => %{cents: "60"}
build(:money)
// => %{cents: "61"}
```
=> Allow setting sequence starting point

config/config.exs, config/test.exs, lib/ex_machina/ecto.ex, priv/test_repo/migrations/1_migrate_all.exs, test/ex_machina/ecto_test.exs, test/support/models/article.ex
Resolves https://github.com/thoughtbot/ex_machina/issues/362
This PR introduces a configuration option to preserve dates when using the `string_params_for` function, making it a non breaking change for now.
Add the following
```
config :ex_machina, preserve_dates: true
```
to your config/test.exs file to enable this.
=> Preserve dates when using string_params_for

lib/ex_machina.ex, lib/ex_machina/sequence.ex
We're actually returning the PID for an Agent rather than a
supervisor.  In addition to being against the erlang callback spec:
```
The function is to return {ok,Pid} or {ok,Pid,State}, where Pid
is the pid of the top supervisor and State is any term. If
omitted, State defaults to []. If the application is stopped
later, State is passed to Module:prep_stop/1.
```
Some tools like phoenix live dashboard will send the
application supervisor supervisor-y messages and end up crashing the
root application tree.
```
** (FunctionClauseError) no function clause matching in Agent.Server.handle_call/3
(elixir 1.14.5) lib/agent/server.ex:11: Agent.Server.handle_call(:which_children, {#PID<0.22073.22>, #Reference<0.3953567925.3593732098.137638>}, %{})
(stdlib 3.17) gen_server.erl:721: …
```
=> feat: ExMachina.start/2: return a supervisor from Application callback

lib/ex_machina/ecto.ex
=> chore: fix typos
